name: Cypress Tests
on:
  push:
env:
  VITE_API_URL: http://localhost:3001
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          build: npm run build
      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: build-folders
          if-no-files-found: error
          path: |
            client/dist
            server/dist
  end-to-end-tests:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download the build folders
        uses: actions/download-artifact@v4
        with:
          name: build-folders
      - name: Run E2E Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run start:ci
          wait-on: 'http://localhost:3000, http://localhost:3001/heroes'
          command: npm run test:e2e:ci